/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DOCDIR "/usr/share/doc"

#define HTMLDIR "/usr/share/doc/html"

#define INCLUDEDIR "/usr/include"

#define INCLUDEDIRSERVER "/usr/include/server"

#define LIBDIR "/usr/lib"

#define LOCALEDIR "/usr/share/locale"

#define MANDIR "/usr/share/man"

#define PGBINDIR "/usr/bin"

#define PGSHAREDIR "/usr/share"

#define PKGINCLUDEDIR "/usr/include"

#define PKGLIBDIR "/usr/lib"

#define SYSCONFDIR "/usr/etc"
